services:
  - type: web
    name: skimpulse-api
    env: node
    rootDir: ./server-deploy
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
